import { createSlice } from "@reduxjs/toolkit";

const userSlice = createSlice({
    name : "user",
    initialState: null,
    reducers:{
        // over here we created different type of reducer function
        addUser:(state,action) =>{
            return action.payload;
        },
        
        removeUser:(state,action) => {
            return null;
        }
    }
});

export default userSlice.reducer; // isko hi store{mystore} aese use krte hai 
// export default userSlice.reducer;
// = ek single reducer function export karta hai
// = jo tere slice ke saare reducers ka combined version hota hai

export const{addUser,removeUser} = userSlice.actions;
// “This line is exporting the action creator functions generated by createSlice. These functions are used to create and dispatch actions to update the Redux store.”